export const DEFAULT_VALUES = {
  NOT_AVAILABLE: 'N/A',
  UNKNOWN: 'Unknown',
  BRAND_LIMIT: 12,
  BRAND_DISPLAY_LIMIT: 6,
  RECENT_PRODUCTS_LIMIT: 8,
  NEW_CAR_MODELS_LIMIT: 8,
  NEW_CAR_MODELS_DISPLAY_LIMIT: 4
} as const
